[build]
  command = "npm install && cd netlify/functions && npm install && cd ../../host && npm install && npm run build"
  publish = "host/dist"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/drawer/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/drawer-ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200